### ISSUE TITLE
Add Drupal Planet Tag for Article Tags

### ISSUE THREAD

**Issue by sean-e-dietrich** [badcamp/badcamp-2019#18]
Drupal Planet taxonomy term must be added to the Tags vocabulary.

**Comment by torenware** [comment]
By default, Drupal 8 does not export vocabulary terms as config items; they appear to be content entities.  

The term "Drupal Planet", however, has been added to the db.  The term currently is linked to Article entities.  Unless we need an updater to check for the term and create it (I think this is overkill), this item is done.

If anyone thinks otherwise, by all means reopen this.
