### ISSUE TITLE
Resyncing config/ directory with active configuration

### ISSUE THREAD

**Issue by torenware** [badcamp/badcamp-2019#29]
While exporting configuration from the current DB for feature/newdesign, the change in the files in the directory was pretty large. I'm guessing that it's been a while since we checked in an export.

Procedure:
```
git checkout feature/newdesign
fin refresh
fin drush cr
# show that config dir is pristine
git status config
fin drush cex
# now see the differences, which are significant
git status config
```

My guess is that this is just a maintenance issue; I'm going to check in the modified directory and put it in a PR.

**Comment by JQTNguyen** [comment]
This issue appears to be a CTA/PSA/Request to have Active Configurations Exported to make sure that what is on LIVE is not lost and blown away by concurrent Development. I'm unsure what all has transpired since the creation of this issue, but if the needs described here are accurate/not off-base, then any more recent needs along these lines should be addressed when https://github.com/badcamp/badcamp-2019/pull/69 is merged.
