### ISSUE TITLE
Change "Article" to "News" for the Article type.

### ISSUE THREAD

**Issue by torenware** [badcamp/badcamp-2019#48]
Looks like the only articles we have are News, so the link used in menus and elsewhere should be changed from "/articles" to "/news".  Should be changed before we make any news live.

**Comment by torenware** [comment]
Trivial to fix; whenever is cool.

**Comment by JQTNguyen** [comment]
The Articles Listing, which appeared on /node/5 on LIVE has been updated, with the Node Title changed to "News", and the URL alias automatically updating to /news accordingly. Because the Menu Link was generated/controlled by settings on the Node, I don't believe any Config Changes are necessary here.
